name: dart_irc_bot
version: 0.0.1
description: A simple console application.
dependencies:
  http: any
  cleverbot: 0.1.0
  xml: any
  markov_dart: 0.1.0
  googleapis: 0.39.0
  googleapis_auth: any
  fortune: any